apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-info-app-service-account
  namespace: cluster-info
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-info-app-reader
rules:
- apiGroups: [""]
  resources: ["nodes","configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-info-app-reader-binding
subjects:
- kind: ServiceAccount
  name: cluster-info-app-service-account
  namespace: cluster-info
roleRef:
  kind: ClusterRole
  name: cluster-info-app-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ClusterResourcePlacement
metadata:
  name: clusterrole-crp
spec:
  resourceSelectors:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      version: v1          
      name: cluster-info-app-reader
  policy:
    placementType: PickAll
---
apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ClusterResourcePlacement
metadata:
  name: clusterrolebinding-crp
spec:
  resourceSelectors:
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      version: v1          
      name: cluster-info-app-reader-binding
  policy:
    placementType: PickAll