apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-info-app-deployment
  namespace: cluster-info
  labels:
    app: cluster-info-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cluster-info-app
  template:
    metadata:
      labels:
        app: cluster-info-app
    spec:
      serviceAccountName: cluster-info-app-service-account
      containers:
      - name: cluster-info-app
        image: msazuredev.azurecr.io/clusterapp:latest
        imagePullPolicy: Always
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 5195
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-info-app-service
  namespace: cluster-info
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5195
  selector:
    app: cluster-info-app
---
apiVersion: networking.fleet.azure.com/v1alpha1
kind: ServiceExport
metadata:
  name: cluster-info-app-service
  namespace: cluster-info
