apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ClusterResourcePlacement
metadata:
  name: clusterrole-crp
spec:
  resourceSelectors:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      version: v1          
      name: cluster-info-app-reader
  policy:
    placementType: PickAll
---
apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ClusterResourcePlacement
metadata:
  name: clusterrolebinding-crp
spec:
  resourceSelectors:
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      version: v1          
      name: cluster-info-app-reader-binding
  policy:
    placementType: PickAll
