apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-info-app-reader
rules:
- apiGroups: [""]
  resources: ["nodes","configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-info-app-reader-binding
subjects:
- kind: ServiceAccount
  name: cluster-info-app-service-account
  namespace: cluster-info
roleRef:
  kind: ClusterRole
  name: cluster-info-app-reader
  apiGroup: rbac.authorization.k8s.io
---
