apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ClusterResourcePlacement
metadata:
  name: cluster-info-namespace-crp
spec:
  resourceSelectors:
    - group: ""
      kind: Namespace
      version: v1          
      name: cluster-info
  policy:
    placementType: PickAll