kind: ConfigMap
apiVersion: v1
data:
  prometheus-config: |-
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: karpenter
      static_configs:
      - targets:
        - karpenter.karpenter:8080
metadata:
  name: ama-metrics-prometheus-config
  namespace: kube-system