apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ClusterResourcePlacement
metadata:
  name: istio-system-namespace-crp
spec:
  resourceSelectors:
    - group: ""
      kind: Namespace
      version: v1          
      name: istio-system
  policy:
    placementType: PickAll