apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ClusterResourcePlacement
metadata:
  name: istio-system-namespace-cro-crp
spec:
  resourceSelectors:
    - group: ""
      kind: Namespace
      version: v1
      name: istio-system
  policy:
    placementType: PickAll
    affinity:
      clusterAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          clusterSelectorTerms:
            - labelSelector:
                matchExpressions:
                - {key: fleet.azure.com/location, operator: In, values: [northeurope, uksouth]}